[mypy]
python_version = 3.9
warn_return_any = False
warn_unused_configs = True
ignore_missing_imports = True
disable_error_code = name-defined

[mypy-flet.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-cryptography.*]
ignore_missing_imports = True

[mypy-winreg]
ignore_errors = True

[mypy-ctypes]
ignore_errors = True

[mypy-src.services.database]
ignore_errors = True

[mypy-src.routers.settings]
ignore_errors = True
