/**
 * Sayings from Epictetus
 * Organized by theme for RAG-powered retrieval
 */

import type { ContentItem } from './content-schema.js';

export const epictetusSayings: ContentItem[] = [
  // On Control & Choice
  {
    id: 'epic-001',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 1',
    section: 'Chapter 1',
    type: 'saying',
    content: 'Some things are up to us and some are not up to us.',
    tags: ['control', 'choice', 'dichotomy', 'stoicism', 'freedom'],
  },
  {
    id: 'epic-002',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '1',
    type: 'saying',
    content: 'Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.',
    tags: ['freedom', 'control', 'goals', 'life', 'disregard'],
  },
  {
    id: 'epic-003',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '5',
    type: 'saying',
    content: 'It is not what happens to you, but how you react to it that matters.',
    tags: ['reaction', 'perception', 'control', 'response', 'mindset'],
  },
  {
    id: 'epic-004',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '8',
    type: 'saying',
    content: 'Do not demand that events should happen as you wish, but wish them to happen as they do, and you will go on well.',
    tags: ['acceptance', 'desire', 'events', 'harmony', 'wishing'],
  },
  // On Self-Examination
  {
    id: 'epic-005',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 1',
    section: 'Chapter 4',
    type: 'saying',
    content: 'It is impossible for a man to learn what he thinks he already knows.',
    tags: ['learning', 'humility', 'knowledge', 'self-awareness'],
  },
  {
    id: 'epic-006',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 2',
    section: 'Chapter 1',
    type: 'saying',
    content: 'First say to yourself what you would be; and then do what you have to do.',
    tags: ['purpose', 'action', 'identity', 'self-knowledge', 'clarity'],
  },
  {
    id: 'epic-007',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '15',
    type: 'saying',
    content: 'Wealth consists not in having great possessions, but in having few wants.',
    tags: ['wealth', 'desire', 'contentment', 'simplicity', 'possessions'],
  },
  {
    id: 'epic-008',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 1',
    section: 'Chapter 29',
    type: 'saying',
    content: 'If you want to improve, be content to be thought foolish and stupid.',
    tags: ['humility', 'learning', 'growth', 'opinion', 'courage'],
  },
  // On Inner Strength
  {
    id: 'epic-009',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 3',
    section: 'Chapter 10',
    type: 'saying',
    content: 'No man is free who is not master of himself.',
    tags: ['freedom', 'self-control', 'mastery', 'discipline', 'autonomy'],
  },
  {
    id: 'epic-010',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '3',
    type: 'saying',
    content: 'If you want to improve, be content to appear, foolish and ignorant with regard to external things.',
    tags: ['humility', 'appearance', 'wisdom', 'learning', 'growth'],
  },
  {
    id: 'epic-011',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '4',
    type: 'saying',
    content: 'When you are going about any action, remind yourself what nature the action is. If you are going to bathe, place before yourself what happens in the bath.',
    tags: ['preparation', 'mindfulness', 'action', 'awareness'],
  },
  {
    id: 'epic-012',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '16',
    type: 'saying',
    content: 'If someone speaks ill of you, do not defend yourself against the accusations, but reply: "You obviously don\'t know about my other vices, otherwise you would have mentioned these as well."',
    tags: ['criticism', 'self-deprecation', 'humor', 'humility', 'response'],
  },
  // On Anger & Emotional Control
  {
    id: 'epic-013',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 1',
    section: 'Chapter 15',
    type: 'saying',
    content: 'If a person gave your body to any stranger he met on his way, you would certainly be angry. And do you feel no shame in handing over your own mind to be confused and mystified by anyone who happens to verbally attack you?',
    tags: ['anger', 'mind', 'control', 'insult', 'self-mastery'],
  },
  {
    id: 'epic-014',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 2',
    section: 'Chapter 18',
    type: 'saying',
    content: 'If a person told your body to a stranger, you would be angry. But you let your mind be confused by anyone who attacks you verbally, and you feel no shame.',
    tags: ['anger', 'mind', 'verbal-attack', 'self-respect'],
  },
  {
    id: 'epic-015',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 3',
    section: 'Chapter 3',
    type: 'saying',
    content: 'Circumstances don\'t make the man, they only reveal him to himself.',
    tags: ['character', 'circumstances', 'self-knowledge', 'truth', 'revelation'],
  },
  {
    id: 'epic-016',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '10',
    type: 'saying',
    content: 'Whenever you find yourself blaming providence for anything that happens, put your hand on your breast and remember: God has given you everything you need to accept it.',
    tags: ['blame', 'providence', 'acceptance', 'gratitude', 'responsibility'],
  },
  // On Death & Transience
  {
    id: 'epic-017',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 3',
    section: 'Chapter 24',
    type: 'saying',
    content: 'Remember from now on that anything difficult to bear is nothing other than a thought; and it is always in your power to dispel it.',
    tags: ['difficulty', 'thought', 'control', 'endurance', 'mind'],
  },
  {
    id: 'epic-018',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 4',
    section: 'Chapter 7',
    type: 'saying',
    content: 'Don\'t explain your philosophy. Embody it.',
    tags: ['action', 'philosophy', 'embodiment', 'practice', 'living'],
  },
  {
    id: 'epic-019',
    author: 'Epictetus',
    source: 'Enchiridion',
    section: '11',
    type: 'saying',
    content: 'Nature has given us one tongue but two ears so that we may listen twice as much as we speak.',
    tags: ['listening', 'speaking', 'wisdom', 'nature', 'communication'],
  },
  {
    id: 'epic-020',
    author: 'Epictetus',
    source: 'Discourses',
    book: 'Book 2',
    section: 'Chapter 14',
    type: 'saying',
    content: 'First learn the meaning of what you say, and then speak.',
    tags: ['speaking', 'understanding', 'wisdom', 'communication', 'clarity'],
  },
];
