/**
 * Excerpts from Marcus Aurelius' "Meditations"
 * Organized by theme for RAG-powered retrieval
 */

import type { ContentItem } from './content-schema.js';

export const meditations: ContentItem[] = [
  // On Self-Discipline & Control
  {
    id: 'med-001',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 8',
    section: '46',
    type: 'excerpt',
    content: 'You have power over your mind - not outside events. Realize this, and you will find strength.',
    tags: ['control', 'strength', 'mind', 'discipline', 'inner-fortress'],
  },
  {
    id: 'med-002',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 2',
    section: '1',
    type: 'excerpt',
    content: 'When you wake up in the morning, tell yourself: The people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous, and surly. They are like this because they cannot tell good from evil. But I have seen the beauty of the good, and the ugliness of the evil, and have recognized that the nature of the wrongdoer is kin to mine.',
    tags: ['morning', 'patience', 'people', 'virtue', 'judgment'],
  },
  {
    id: 'med-003',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 6',
    section: '27',
    type: 'excerpt',
    content: 'Reject your sense of injury and the injury itself disappears.',
    tags: ['injury', 'perception', 'letting-go', 'resilience'],
  },
  {
    id: 'med-004',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 4',
    section: '3',
    type: 'excerpt',
    content: 'The happiness of your life depends upon the quality of your thoughts; therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature.',
    tags: ['happiness', 'thoughts', 'virtue', 'mindfulness', 'quality'],
  },
  {
    id: 'med-005',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 12',
    section: '16',
    type: 'excerpt',
    content: 'You could leave life right now. Let that determine what you do and say and think.',
    tags: ['death', 'memento-mori', 'urgency', 'presence', 'priorities'],
  },
  {
    id: 'med-006',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 5',
    section: '16',
    type: 'excerpt',
    content: 'The best revenge against an unkind person is not to be like them.',
    tags: ['revenge', 'kindness', 'virtue', 'character', 'self-mastery'],
  },
  {
    id: 'med-007',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 2',
    section: '11',
    type: 'excerpt',
    content: 'Begin each act of your life as though it were your last.',
    tags: ['presence', 'death', 'focus', 'purpose', 'action'],
  },
  {
    id: 'med-008',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 4',
    section: '43',
    type: 'excerpt',
    content: 'It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.',
    tags: ['self-worth', 'opinion', 'self-love', 'authenticity'],
  },
  {
    id: 'med-009',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 3',
    section: '5',
    type: 'excerpt',
    content: 'Do not waste the remainder of thy life on images of others, unless it be for the common good.',
    tags: ['wasting-time', 'focus', 'common-good', 'purpose'],
  },
  {
    id: 'med-010',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 5',
    section: '1',
    type: 'excerpt',
    content: 'At dawn, when you have difficulty getting out of bed, tell yourself: "I have to go to work — as a human being. What do I have to complain about, if I\'m going to do what I was born for — the things I was brought into the world to do?".',
    tags: ['work', 'purpose', 'morning', 'duty', 'motivation'],
  },
  // On Acceptance & Nature
  {
    id: 'med-011',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 4',
    section: '49',
    type: 'excerpt',
    content: 'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.',
    tags: ['distress', 'perception', 'acceptance', 'control', 'pain'],
  },
  {
    id: 'med-012',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 7',
    section: '14',
    type: 'excerpt',
    content: 'Either the world is a confusion or a providential order. Be a city to thyself.',
    tags: ['nature', 'order', 'self-reliance', 'stoicism'],
  },
  {
    id: 'med-013',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 8',
    section: '47',
    type: 'excerpt',
    content: 'If it is not right do not do it; if it is not true do not say it.',
    tags: ['truth', 'right-action', 'integrity', 'ethics'],
  },
  {
    id: 'med-014',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 10',
    section: '35',
    type: 'excerpt',
    content: 'Nothing happens to anybody which he is not fitted by nature to bear. The same things happen to another, either because of his ignorance they happened to him, or to show his bravery, he is firm and undisturbed.',
    tags: ['strength', 'resilience', 'nature', 'endurance', 'adversity'],
  },
  {
    id: 'med-015',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 4',
    section: '39',
    type: 'excerpt',
    content: 'Be tolerant with others and strict with yourself.',
    tags: ['tolerance', 'self-discipline', 'humility', 'growth'],
  },
  {
    id: 'med-016',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 12',
    section: '1',
    type: 'excerpt',
    content: 'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.',
    tags: ['opinion', 'truth', 'perception', 'wisdom', 'perspective'],
  },
  {
    id: 'med-017',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 8',
    section: '39',
    type: 'excerpt',
    content: 'Choose not to be harmed, and you won\'t feel harmed. Don\'t feel harmed, and you haven\'t been.',
    tags: ['harm', 'choice', 'perception', 'resilience', 'control'],
  },
  {
    id: 'med-018',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 2',
    section: '5',
    type: 'excerpt',
    content: 'Stop allowing your mind to be dragged by external impressions like a puppet on strings.',
    tags: ['mind-control', 'autonomy', 'freedom', 'inner-peace'],
  },
  {
    id: 'med-019',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 6',
    section: '13',
    type: 'excerpt',
    content: 'The universe is change; our life is what our thoughts make it.',
    tags: ['change', 'thoughts', 'mindset', 'life'],
  },
  {
    id: 'med-020',
    author: 'Marcus Aurelius',
    source: 'Meditations',
    book: 'Book 9',
    section: '29',
    type: 'excerpt',
    content: 'How much time he gains who does not look to see what his neighbor says or does or thinks, but only at what he does himself to make it just and holy.',
    tags: ['focus', 'self-improvement', 'judgment', 'righteousness'],
  },
];
