/**
 * Quotes from Seneca the Younger
 * Organized by theme for RAG-powered retrieval
 */

import type { ContentItem } from './content-schema.js';

export const senecaQuotes: ContentItem[] = [
  // On Strength & Resilience
  {
    id: 'sen-001',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 13',
    type: 'quote',
    content: 'We suffer more often in imagination than in reality.',
    tags: ['suffering', 'imagination', 'reality', 'fear', 'anxiety'],
  },
  {
    id: 'sen-002',
    author: 'Seneca',
    source: 'On Providence',
    section: '4',
    type: 'quote',
    content: 'Difficulties strengthen the mind, as labor does the body.',
    tags: ['strength', 'difficulty', 'growth', 'resilience', 'mind'],
  },
  {
    id: 'sen-003',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 107',
    type: 'quote',
    content: 'The wise man is content with his lot, whatever it may be, without wishing for what he has not.',
    tags: ['contentment', 'wisdom', 'gratitude', 'acceptance'],
  },
  {
    id: 'sen-004',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 12',
    type: 'quote',
    content: 'It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.',
    tags: ['courage', 'fear', 'action', 'difficulty', 'daring'],
  },
  {
    id: 'sen-005',
    author: 'Seneca',
    source: 'On the Shortness of Life',
    section: '1',
    type: 'quote',
    content: 'It is not that we have a short time to live, but that we waste a great deal of it. Life is long enough, and it has been given in sufficiently generous measure to allow the accomplishment of the greatest things, if the whole of it is well invested.',
    tags: ['time', 'waste', 'life', 'purpose', 'priorities'],
  },
  {
    id: 'sen-006',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 41',
    type: 'quote',
    content: 'If a man knows not to port he sails, no wind is favorable.',
    tags: ['purpose', 'direction', 'goals', 'clarity'],
  },
  // On Anger & Emotion
  {
    id: 'sen-007',
    author: 'Seneca',
    source: 'On Anger',
    section: 'Book 1',
    type: 'quote',
    content: 'The greatest remedy for anger is delay.',
    tags: ['anger', 'patience', 'delay', 'emotion', 'control'],
  },
  {
    id: 'sen-008',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 75',
    type: 'quote',
    content: 'We are more often frightened than hurt; and we suffer more from imagination than from reality.',
    tags: ['fear', 'imagination', 'suffering', 'courage', 'reality'],
  },
  {
    id: 'sen-009',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 5',
    type: 'quote',
    content: 'The mind that is anxious about the future is miserable.',
    tags: ['anxiety', 'future', 'present', 'mindfulness'],
  },
  {
    id: 'sen-010',
    author: 'Seneca',
    source: 'On Tranquility of Mind',
    section: '12',
    type: 'quote',
    content: 'There is no easy path from the outside to the inside. Peace can be reached through the practice of philosophy.',
    tags: ['peace', 'philosophy', 'inner-life', 'tranquility'],
  },
  // On Wisdom & Virtue
  {
    id: 'sen-011',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 95',
    type: 'quote',
    content: 'It is the quality of a wise man to examine everything, but especially his own life.',
    tags: ['wisdom', 'self-reflection', 'examination', 'self-improvement'],
  },
  {
    id: 'sen-012',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 25',
    type: 'quote',
    content: 'Associate with those who will make a better human of you.',
    tags: ['friendship', 'growth', 'association', 'character'],
  },
  {
    id: 'sen-013',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 70',
    type: 'quote',
    content: 'It is not the man who has too little, but the man who craves more, that is poor.',
    tags: ['poverty', 'greed', 'contentment', 'wealth', 'desire'],
  },
  {
    id: 'sen-014',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 87',
    type: 'quote',
    content: 'True happiness is to enjoy the present, without anxious dependence upon the future.',
    tags: ['happiness', 'present', 'future', 'contentment', 'peace'],
  },
  {
    id: 'sen-015',
    author: 'Seneca',
    source: 'On the Shortness of Life',
    section: '7',
    type: 'quote',
    content: 'People are frugal in guarding their personal property; but as soon as it comes to squandering time they are most wasteful of the one thing in which it is right to be stingy.',
    tags: ['time', 'money', 'waste', 'value', 'priorities'],
  },
  {
    id: 'sen-016',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 53',
    type: 'quote',
    content: 'Luck is what happens when preparation meets opportunity.',
    tags: ['luck', 'preparation', 'opportunity', 'action'],
  },
  // On Adversity & Fortune
  {
    id: 'sen-017',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 85',
    type: 'quote',
    content: 'A gem cannot be polished without friction, nor a man perfected without trials.',
    tags: ['adversity', 'growth', 'trials', 'character', 'perfection'],
  },
  {
    id: 'sen-018',
    author: 'Seneca',
    source: 'On Providence',
    section: '2',
    type: 'quote',
    content: 'Fire is the test of all things, and adversity is the test of brave men.',
    tags: ['adversity', 'courage', 'testing', 'resilience', 'strength'],
  },
  {
    id: 'sen-019',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 71',
    type: 'quote',
    content: 'Throw me to the wolves and I will return leading the pack.',
    tags: ['resilience', 'strength', 'adversity', 'leadership'],
  },
  {
    id: 'sen-020',
    author: 'Seneca',
    source: 'Letters to Lucilius',
    letter: 'Letter 9',
    type: 'quote',
    content: 'The foolish man, though a king, will call himself a slave; and the wise man though a slave, will call himself a king.',
    tags: ['wisdom', 'freedom', 'slavery', 'mind', 'perspective'],
  },
];
